- name: This playbook will provision ubuntu and centos containers
  hosts: localhost
  become: yes
  tasks:
    - name: Install Extra Packages for Enterprise Linux(EPEL) in CentOS
      when: ansible_distribution == "CentOS"
      yum: name=epel-release state=latest

    - name: Install PIP in CentOS
      when: ansible_distribution == "CentOS"
      yum: name=python3-pip state=latest

    - name: Install Docker Python SDK
      shell: pip3 install docker-py

    - name: Remove existing ubuntu containers
      shell: docker rm -f $(docker ps -aq --filter="name=ubuntu*|centos*")

    - name: Provision ubuntu containers
      docker_container:
           name: "ubuntu-{{item}}"
           hostname: "ubuntu-{{item}}"
           image: tektutor/ansible-ubuntu-node:latest
           state: started
           ports:
             - "2{{item}}:22"
             - "8{{item}}:80"
      with_sequence: start=1 end=2 format="%03d"

    - name: Provision centos containers
      docker_container:
           name: "centos-{{item}}"
           hostname: "centos-{{item}}"
           image: tektutor/ansible-centos-node:latest
           state: started
           ports:
             - "3{{item}}:22"
             - "9{{item}}:80"
      with_sequence: start=1 end=2 format="%03d"


